export const projects = [
  {
    src: "/p-1.png",
    id: "huella",
    title: "Huella",
    description: "descripcion del trabajo",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-pnpm.svg" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
  {
    src: "/p-2.png",
    id: "portafolio-2023",
    title: "Portafolio 2023",
    description: "descripcion del trabajo",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-npm.png" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
  {
    src: "/p-6.png",
    id: "Portafolio-2023",
    title: "Portafolio 2025",
    description: "descripcion del trabajo ",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-npm.png" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
  {
    src: "/p-5.png",
    id: "landing",
    title: "Landing",
    description: "descripcion del trabajo",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-npm.png" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
  {
    src: "/p-3.png",
    id: "ansser",
    title: "Ansser",
    description: "descripcion del trabajo",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-npm.png" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
  {
    src: "/p-4.png",
    id: "funnel",
    title: "Funnel",
    description: "descripcion del trabajo",
    tecnologies: [
      { name: "react", img: "./logo-react.svg" },
      { name: "css", img: "./logo-css.svg" },
      { name: "js", img: "./logo-javascript.svg" },
      { name: "npm", img: "./logo-npm.png" },
      { name: "vite", img: "./logo-vite.svg" },
    ],
    demo: false,
  },
];
